FROM node:20-alpine

WORKDIR /app

COPY interface/dashboard/package.json /app/package.json
RUN npm install

COPY interface/dashboard /app

ARG NEXT_PUBLIC_API_BASE
ENV NEXT_PUBLIC_API_BASE=$NEXT_PUBLIC_API_BASE

ARG NEXT_PUBLIC_API_WRITE_KEY
ENV NEXT_PUBLIC_API_WRITE_KEY=$NEXT_PUBLIC_API_WRITE_KEY

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
